language: python

# Use container-base infrastructure
sudo: false

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
  services:
    - xvfb

install:
  - pip3 install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script:
  - xvfb-run make test
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - python3 RAASNet.py
